name: Waka Readme
# https://github.com/anmol098/waka-readme-stats
on:
  schedule:
    # Runs at 04:30am CST
    - cron: '30 20 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "False"
          # SHOW_SHORT_INFO: "False"
          # SHOW_LOC_CHART: "False"
          IGNORED_REPOS: "myyyy.github.com"
